// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// SampleRouterInterface is an autogenerated mock type for the SampleRouterInterface type
type SampleRouterInterface struct {
	mock.Mock
}

// Router provides a mock function with given fields: c
func (_m *SampleRouterInterface) Router(c *echo.Group) {
	_m.Called(c)
}
