name: sample-CD
on:
  push:
    branches:
      - master
jobs:
  staging-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to ECR
        id: ecr
        uses: elgohr/ecr-login-action@1.0.1
        with:
          access_key: ${{ secrets.AWS_STAGING_ACCESS_KEY }}
          secret_access_key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
      - name: Build image and publish it to staging registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 521664337176.dkr.ecr.us-east-1.amazonaws.com/sample
          username: ${{ steps.ecr.outputs.username }}
          password: ${{ steps.ecr.outputs.password }}
          registry: ${{ steps.ecr.outputs.registry }}
          snapshot: true
          dockerfile: Dockerfile
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
        uses: edge/simple-slack-notify@master
        with:
          channel: "#sample-alerts"
          status: ${{ job.status }}
          success_text: "${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) image pushed successfully to staging ECR"
          failure_text: "${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) image build failed"
          cancelled_text: "${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) build was cancelled"
          fields: |
            [{ "title": "Repository", "value": "${env.GITHUB_REPOSITORY}", "short": true },
            { "title": "Branch", "value": "${{ steps.extract_branch.outputs.branch }}", "short": true },
            { "title": "Author", "value": "${env.GITHUB_ACTOR}", "short": true }]
